name: Tests
on:
  pull_request:
    branches:
      - master
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run unit tests
        run: npm test
